runtime: java17
instance_class: F1

entrypoint: java -jar ems-backend-0.0.1-SNAPSHOT.jar

env_variables:
  SPRING_PROFILES_ACTIVE: "default"
  DB_NAME: "tenant-db"
  DB_USER: "root"
  DB_PASSWORD: "Dhanush@123456"
  INSTANCE_CONNECTION_NAME: "java-backend-460409:us-central1:multitenant-db"