apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-backend-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/Dhanush19B61A0550/minikube-gitops-backend.git'
    targetRevision: main
    path: k8s

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
